---
# creates a new cluster scope role to watch for resource status changes
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: resource_watcher
rules:
  - apiGroups: ["*"] # all api groups
    resources: [
      "pods",
      "secrets",
      "configmaps",
      "services",
      "deployments",
      "namespaces",
      "persistentvolumes",
      "replicasets",
      "serviceaccounts",
      "clusterroles",
      "jobs",
      "ingresses",
      "daemonsets",
      "replicationcontrollers"
    ]
    verbs: ["get", "watch", "list"]
---
# creates the Service account used by the Sentinel
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sentinel
  namespace: default
---
# grants the Sentinel service account the privileges of the ResourceWatcher cluster role
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: sentinel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: resource_watcher
subjects:
  - kind: ServiceAccount
    name: sentinel
    namespace: default
...